language: node_js
node_js:
  - '8'
  - '6'
  - '4'
cache:
  directories:
    - $HOME/.npm
before_install:
  - 'npm install --global npm@5.6.0'
  - 'npm --version'
after_success: 'npx codecov --file=./coverage/lcov.info'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
